### PR TITLE
Pad sponsor logos

### PR DESCRIPTION
**Pull request by SolarDrew**
Add a new sponsor-logo class to the CSS theme and use it for the logos. Did it this way because then it only affects those images and not any others or the ones from previous years.

Does require a `:class: sponsor-logo` when defining the image.

### CODE REVIEW

**Comment by bsipocz** [comment]
The logo is now missing....

**Comment by SolarDrew** [comment]
That's odd. It's still there for me (firefox).

**Comment by bsipocz** [comment]
I'm also on firefox, but no logo, just the text. Also tried from incognito window, nothing there either. No logo from chrome either.

**Comment by Cadair** [comment]
yep, I can't see it either.

**Pull request merged**
